name: cha_lan
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  cloud_firestore: ^6.0.1
  dio: ^5.9.0
  firebase_auth: ^6.0.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  font_awesome_flutter: ^10.10.0
  google_generative_ai: ^0.4.7
  provider: ^6.1.5+1
  riverpod: ^3.0.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
