// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjq1H4gUk2l-l4Siv-ZsVQNdKUKGUudbw',
    appId: '1:14977791558:web:49c22b7290a8f8ee16fc47',
    messagingSenderId: '14977791558',
    projectId: 'chalan-11b87',
    authDomain: 'chalan-11b87.firebaseapp.com',
    storageBucket: 'chalan-11b87.firebasestorage.app',
    measurementId: 'G-GSY8EFM67N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiaqRZsBi_EtiUhq3s4EBDaI5FUD5Talw',
    appId: '1:14977791558:android:c8777962ca77704f16fc47',
    messagingSenderId: '14977791558',
    projectId: 'chalan-11b87',
    storageBucket: 'chalan-11b87.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRqjpcRJRQ7RTzhB4EjWO_PS7SY2B8YhI',
    appId: '1:14977791558:ios:2e14c0e2da2e8c0916fc47',
    messagingSenderId: '14977791558',
    projectId: 'chalan-11b87',
    storageBucket: 'chalan-11b87.firebasestorage.app',
    iosBundleId: 'com.example.chaLan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRqjpcRJRQ7RTzhB4EjWO_PS7SY2B8YhI',
    appId: '1:14977791558:ios:2e14c0e2da2e8c0916fc47',
    messagingSenderId: '14977791558',
    projectId: 'chalan-11b87',
    storageBucket: 'chalan-11b87.firebasestorage.app',
    iosBundleId: 'com.example.chaLan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjq1H4gUk2l-l4Siv-ZsVQNdKUKGUudbw',
    appId: '1:14977791558:web:53c105a9006e981e16fc47',
    messagingSenderId: '14977791558',
    projectId: 'chalan-11b87',
    authDomain: 'chalan-11b87.firebaseapp.com',
    storageBucket: 'chalan-11b87.firebasestorage.app',
    measurementId: 'G-7JVXKFQSMJ',
  );
}
